<?php
    // This file contains longer descriptions and locations of each venue
    // displayed 

    $descriptions = array(
                            "Central Plaza" => array("Derbyshire", "Welcome to Central Plaza- what if you never had to have a big wedding in a church in an all-too formal setting? Central Plaza is the venue for those who do not want to have too much pressure on their wedding and would rather have the homely comforts. This venue can hold up to 200 people for your wedding if you choose, and, after the big event, you can step out into the fresh air and look up at all the lights overhead, twinkling like stars- a match made in heaven. Why wouldn’t you choose pure comfort and relaxation?"),
                            "Pacific Towers Hotel" => array("Los Angeles", "Welcome to Pacific Towers Hotel, an unforgettable fusion of nature and humankind. Look ahead to the sparkling Pacific, home to spectacular wildlife, such as bottle-nose dolphins and humpback whales. Could you be lucky enough to spot one of these magnificent creatures on your special day? Then, look behind you to the industrial expanse that is the City of Angels, filled the hub-bub of a busy and truly unique city. This venue can hold up to 250 people, perfect for making you and your love stars for the day – you’ll feel right at home among the rich and famous!"),
                            "Sky Center Complex" => array("London", "Welcome to Sky Center Complex- a minimalist and modern dream is waiting for you. The contemporary appearance of the venue is very apt to those who do not prefer to surround themselves in a historical atmosphere and would much rather look to the future. In contrast to the modernistic and sleek venue, the view from beyond explodes with colour, creating a fusion of grace and natural beauty. What could be more bewitching?"),
                            "Sea View Tavern" => array("Malé", "Welcome to the Sea View Tavern- imagine a heavenly sunset behind you, shining its iridescent rays of light upon your wedding; imagine the ocean lapping at your feet, sparkling, and shimmering like diamonds; imagine the peaceful atmosphere created by such as a place as this. The wide expanse of the beach can hold up to 300 guests, making sure that there are no limits to your imagination. Sea View Tavern is sure to give you the romantic getaway of your dreams, so, why not indulge in pure luxury?"),
                            "Ashby Castle" => array("Bavaria", "Welcome to Ashby Castle. Tucked away in the valleys of Bavaria, this venue is perfect for a large weddings, boasting a huge capacity of 1000 people. You can live out your childhood dreams in this historically-rich castle, which happens to be the inspiration for many Disney castles! Doesn’t that sound truly magical? You will have complete freedom in the castle, being able to climb its 750 steps although the way to its highest turret, and then all the way back down to explore its dungeons. This will certainly be an incredible and unique wedding! "),
                            "Fawlty Towers" => array("Brighton", "Welcome to Faulty Towers- untrue to its name, Faulty Towers is a small, cosy castle. However, this castle can quickly feel like a home with its vintage décor and friendly staff ready to meet your every need. Faulty towers can house up to 50 people so is perfect for small-scale events and guestlists- what is small in numbers is made up for by the flourishing scenery surrounding the grounds that brings everything to life. If you are looking for a quiet, yet stylish wedding, this is the place for you!"),
                            "Hilltop Mansion" => array("Lake District", "Welcome to Hilltop Mansion, a true symbiosis of the best nature has to offer. Perched on an isolated peak in the Lake District, you will be in awe at the panoramic views around you – from the deep valleys and lake, to neighbouring mountains. Then, take a step inside the incredible 18th century mansion and experience a wedding like no other. This venue can hold up to 120 people, perfect for a small wedding with just closest friends and family. Surrounded by pristine architecture, stylish decoration, and unbeatable views, what more could you want in a unforgettable day?"),
                            "Haslegrave Hotel" => array("Loughborough", "Welcome to Hazelgrave Hotel- if ever since you were little, you dreamed upon the brightest star in the sky that you would find your one true love, this is the place for you! This secluded castle in the middle of the lush green forest with antique, opulently- designed rooms is the epitome of escapism and romance, as if extracted straight from a novel. If you are looking for an outdoor wedding, the grounds have an awe-inspiring view of all that nature has to offer. There is nowhere better than Hazelgrave Hotel for a fairy-tale wedding!"),
                            "Forest Inn" => array("Gloucester", "Welcome to the Forest Inn- rustic lodgings, lavish green accents and autumn leaves falling all around you. Here, nature encompasses you wherever you go in this beautiful, secluded utopia. Up to 260 guests can be invited to your wedding for those who prefer larger events, and the venue is open all year round for those spring weddings with blooming flowers and bright sunshine, or winter weddings with warm, cosy halls and adornments of snow. Whatever the wish, Forest Inn can make it a reality."),
                            "Southwestern Estate" => array("Peak District", "Welcome to Southwestern Estate. Situated in the valleys of the peak district, this stately home can be your home for the day! Let the impeccable grounds whisk you away to your wildest dreams. The estate’s stunning grounds span for miles, also providing home to deer, horses, and owls, which you can meet accompanied by trained staff. In addition, luxuriate in the surroundings of our sublime manicured garden. The decadent interiors of our luxury manor house make everyone feel like royalty, if you’re looking for the celebrity experience then the Southwestern Estate is your wedding destination!")
    );

    $venuename = $_REQUEST["venuename"];
    $result = $descriptions[$venuename];

    echo json_encode($result);
?>